package com.frasesromanticas.provider

class FrasesProvider {
    val frases = listOf(
        "Se o amor fosse um perfume, você seria a essência que nunca se esgota no meu coração.",
        "Nos seus olhos, encontrei um universo onde quero me perder para sempre.",
        "Cada batida do meu coração sussurra seu nome, porque amar você é minha melodia favorita.",
        "Você é o sonho que eu nunca quero acordar.",
        "O meu lar é onde você está.",
        "Seu sorriso ilumina até meus dias mais nublados.",
        "Meu mundo é muito mais bonito desde que você chegou.",
        "Se o amor fosse uma música, você seria minha canção favorita.",
        "Amar você é como respirar: essencial e natural.",
        "Eu me perco no brilho dos seus olhos e não quero me encontrar.",
        "Segurar sua mão é segurar a felicidade.",
        "O melhor lugar do mundo é dentro do seu abraço.",
        "Você é a poesia que faltava nos meus dias.",
        "No seu amor, encontrei minha paz.",
        "Se amar é loucura, então quero ser eternamente insano por você.",
        "Cada instante ao seu lado é um presente do destino.",
        "Você é a certeza mais bonita que já tive.",
        "Meu coração bate no ritmo do seu.",
        "Eu não preciso de nada além do seu amor para ser feliz.",
        "Você é a melhor parte dos meus dias.",
        "Seu nome virou sinônimo de felicidade para mim.",
        "Meu coração é seu e sempre será.",
        "Seu amor me ensina a ser melhor a cada dia.",
        "Você é o meu 'felizes para sempre'.",
        "Seu abraço é o meu lugar favorito no mundo.",
        "Você é minha história preferida e eu quero escrevê-la para sempre.",
        "Amar você é o meu maior privilégio.",
        "Eu trocaria mil vidas por uma só ao seu lado.",
        "Seu olhar tem o poder de transformar tudo ao meu redor.",
        "Com você, até o silêncio é confortável.",
        "Você é a resposta para todas as minhas orações.",
        "O amor tem seu nome e seu cheiro.",
        "Você é o meu destino favorito.",
        "Cada segundo sem você é uma eternidade.",
        "Você é o doce que faltava na minha vida.",
        "Seu amor colore meu mundo.",
        "Você é a estrela que guia meus sonhos.",
        "Seus beijos são a melhor parte do meu dia.",
        "Meu maior medo é imaginar um mundo sem você.",
        "Você é a melhor decisão que já tomei.",
        "O amor verdadeiro tem seu rosto.",
        "Ao seu lado, a vida faz mais sentido.",
        "Seus carinhos são a cura para qualquer tristeza.",
        "Cada 'eu te amo' seu é música para minha alma.",
        "Seu toque acende todas as estrelas do meu céu.",
        "No seu amor, encontrei meu refúgio.",
        "Sua risada é minha melodia favorita.",
        "Você é a melhor surpresa que a vida já me deu.",
        "Eu te amo mais do que as palavras podem expressar",
        "Cada dia ao seu lado é um presente",
        "Eu te amo hoje e sempre",
        "Você é a razão da minha felicidade",
        "Meu amor por você não tem limites",
        "Estar com você é como viver um conto de fadas",
        "Nosso amor é minha maior sorte",
        "Você é minha pessoa favorita no mundo",
        "Não há nada que eu queira mais do que estar ao seu lado",
        "Nosso amor é a minha maior aventura",
        "Você é a melodia que faz meu coração cantar",
        "Meu mundo é mais bonito porque você está nele",
        "Eu escolheria você em todas as vidas",
        "O amor que sinto por você só cresce",
        "Cada momento com você é precioso",
        "Você é o melhor presente da minha vida",
        "Seu amor me faz mais forte",
        "Você e eu somos perfeitos juntos",
        "Te amar é minha coisa favorita",
        "Você é o sol nos meus dias nublados",
        "Meu amor por você é eterno",
        "Você faz meu coração sorrir",
        "Estar com você é o melhor lugar para estar",
        "Você é a peça que faltava no meu quebra-cabeça",
        "Nosso amor é único e especial",
        "Com você, tudo se torna mais belo",
        "Eu sou mais feliz porque tenho você",
        "Seu amor é o que me move",
        "Você faz cada momento valer a pena",
        "Nada se compara ao que sinto por você",
        "Você é a estrela que guia meu caminho",
        "O amor que sinto por você é infinito",
        "Nada me faz mais feliz do que estar com você",
        "Você faz meu coração pulsar mais forte",
        "Você me faz acreditar no amor verdadeiro",
        "Não há distância que possa separar nossos corações",
        "Você é o melhor capítulo da minha história",
        "Seu amor é a luz que ilumina meu caminho.",
        "Cada momento ao seu lado transforma a vida em poesia.",
        "Nos seus braços, encontrei o abraço que sempre procurei.",
        "Você é a história mais linda que o destino escreveu para mim.",
        "Meu coração encontrou seu ritmo no compasso do seu amor.",
        "O brilho dos seus olhos é o reflexo da minha felicidade.",
        "Não há sonho mais belo do que viver ao seu lado.",
        "Sua voz é a melodia que embala meus dias.",
        "Seu amor é o segredo da minha eterna felicidade.",
        "No seu sorriso, encontro a paz que o mundo não pode me dar.",
        "Seus olhos refletem o amor que ilumina minha alma, e neles encontro o meu eterno abrigo.",
        "Cada suspiro meu carrega seu nome, porque te amar é o meu maior motivo para respirar.",
        "O universo pode ser infinito, mas nada nele se compara ao espaço que você ocupa no meu coração.",
        "Seu amor é como uma constelação que guia meu destino, brilhando forte em cada passo que dou.",
    )
}